name: my first workflow

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: welcome message
        run: echo Welcome to my first workflow!

      - name: list files
        run: ls -al

      - name: read me file
        run: cat README.md
